apiVersion: v1
kind: Pod
metadata:
  name: pyserver
spec:
  containers:
  - name: pyserver
    image: 384845845052/pyserver:v0.1
    ports:
    - containerPort: 5001
    volumeMounts:
    - mountPath: "/usr/src/app/users.json"
      subPath: "users.json"
      name: users-volume
  volumes:
   - name: users-volume
     configMap:
        name: users-conf
      
      